# Generated by Django 2.2 on 2019-04-14 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandName', models.CharField(help_text='Nombre de Marca de vehiculos', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ToRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toRevisionKm', models.PositiveIntegerField(default=None, help_text='Kilometraje a revisar')),
                ('toRevisionDate', models.DateField(blank=True, default=None, editable=False, help_text='Fecha estimada a revisar', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceName', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('toRevision', models.ManyToManyField(blank=True, help_text='Revisiones programadas', to='registro.ToRevision')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(help_text='Nombre del dueño del vehiculo', max_length=50)),
                ('phone', models.CharField(blank=True, help_text='Telefono del dueño del vehiculo', max_length=50, null=True)),
                ('email', models.EmailField(blank=True, help_text='email del dueño del vehiculo', max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owner_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owner_modified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colorCar', models.CharField(choices=[('red', 'Rojo'), ('blue', 'Azul'), ('white', 'Blanco'), ('Green', 'Verde'), ('Gray', 'Gris'), ('Yellow', 'Amarillo'), ('Vine', 'Vino'), ('maroon', 'Marron'), ('Olive', 'Olivo'), ('beige', 'Beige'), ('silver', 'Plata'), ('gold', 'Dorado')], help_text='Color del vehiculo', max_length=50)),
                ('modelCar', models.CharField(help_text='Modelo del vehiculo', max_length=50)),
                ('yearCar', models.PositiveIntegerField(help_text='Año del vehiculo')),
                ('carPlate', models.CharField(blank=True, default=None, help_text='Placa del vehiculo', max_length=10, null=True)),
                ('kmDailyAverage', models.PositiveIntegerField(blank=True, default=None, help_text='Promedio Diario en Kilometros', null=True)),
                ('kmActual', models.PositiveIntegerField(blank=True, default=None, help_text='Kilometraje actual', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('brandCar', models.ForeignKey(blank=True, default=None, help_text='Marca del vehiculo', null=True, on_delete=django.db.models.deletion.PROTECT, to='registro.BrandCar')),
                ('owner', models.ForeignKey(blank=True, default=None, help_text='Dueño del vehiculo', null=True, on_delete=django.db.models.deletion.PROTECT, to='registro.Owner')),
            ],
        ),
    ]
