# Generated by Django 2.2 on 2019-04-14 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecatalog',
            name='toRevision',
            field=models.ManyToManyField(blank=True, help_text='Revisiones programadas', null=True, to='registro.ToRevision'),
        ),
    ]
