# Generated by Django 2.2 on 2019-04-14 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_auto_20190413_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecatalog',
            name='toRevision',
            field=models.ManyToManyField(help_text='Revisiones programadas', to='registro.ToRevision'),
        ),
    ]
