# Generated by Django 2.2 on 2019-04-14 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_register'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='RegisterService',
        ),
    ]
