# Generated by Django 2.2 on 2019-04-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_auto_20190413_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerservice',
            name='dateOfUpdated',
            field=models.DateField(blank=True, editable=False, help_text='Fecha de Actualizacion', null=True),
        ),
    ]
